import * as React from "react"
import { indoku } from "../primitives/indoku"

export const chartTokens = { size: { sm: 160, md: 220, lg: 300 }, spacing: { sm: 4, md: 8, lg: 16 }, padding: { top: 14, right: 16, bottom: 26, left: 44 } } as const
export type ChartValue = number | null
export interface ChartSeries { name?: string; color?: string; values: ChartValue[]; axis?: "left" | "right"; dashed?: boolean }
export type ChartFormat = (value: number) => string
export const compactFormat: ChartFormat = (value) => new Intl.NumberFormat(undefined, { notation: "compact", maximumFractionDigits: 2 }).format(value)
export function sortChartData<T>(data: T[], by: (item: T) => number, direction: "asc" | "desc" = "desc"): T[] { return [...data].sort((a, b) => direction === "asc" ? by(a) - by(b) : by(b) - by(a)) }
export function niceDomain(min: number, max: number, count = 5): { ticks: number[]; domain: [number, number] } {
  if (!Number.isFinite(min) || !Number.isFinite(max)) return { ticks: [0, 1], domain: [0, 1] }
  if (min === max) max = min + 1
  const raw = (max - min) / Math.max(1, count), magnitude = 10 ** Math.floor(Math.log10(raw)), normalized = raw / magnitude
  const step = (normalized < 1.5 ? 1 : normalized < 3 ? 2 : normalized < 7 ? 5 : 10) * magnitude
  const start = Math.floor(min / step) * step, end = Math.ceil(max / step) * step, ticks: number[] = []
  for (let value = start; value <= end + step / 2; value += step) ticks.push(Math.round(value / step) * step)
  return { ticks, domain: [start, end] }
}
const Root = indoku("div"), LegendRoot = indoku("div"), LegendButton = indoku("button")
const PALETTE = ["var(--indoku-colors-accent-default)", "var(--indoku-colors-status-success)", "var(--indoku-colors-status-warning)", "var(--indoku-colors-status-danger)", "var(--indoku-colors-status-info)", "var(--indoku-colors-fg-muted)"]
const resolveColor = (value: string | undefined, index: number) => {
  const semantic: Record<string, string> = { accent: "var(--indoku-colors-accent-default)", success: "var(--indoku-colors-status-success)", ok: "var(--indoku-colors-status-success)", warning: "var(--indoku-colors-status-warning)", danger: "var(--indoku-colors-status-danger)", info: "var(--indoku-colors-status-info)", muted: "var(--indoku-colors-fg-muted)" }
  return value ? semantic[value] ?? value : PALETTE[index % PALETTE.length]!
}
export interface UseChartOptions { series?: { name?: string; color?: string }[]; format?: ChartFormat; highlight?: number | null }
export interface ChartApi { colors: string[]; format: ChartFormat; active: number | null; setActive: (index: number | null) => void; opacity: (index: number) => number; legendProps: (index: number) => { onMouseEnter: () => void; onMouseLeave: () => void; onFocus: () => void; onBlur: () => void }; tokens: typeof chartTokens }
export function useChart({ series = [], format = compactFormat, highlight }: UseChartOptions = {}): ChartApi {
  const [hovered, setHovered] = React.useState<number | null>(null)
  const active = hovered ?? highlight ?? null
  const colors = React.useMemo(() => series.map((item, index) => resolveColor(item.color, index)), [series])
  return { colors, format, active, setActive: setHovered, opacity: (index) => active == null || active === index ? 1 : 0.28, legendProps: (index) => ({ onMouseEnter: () => setHovered(index), onMouseLeave: () => setHovered(null), onFocus: () => setHovered(index), onBlur: () => setHovered(null) }), tokens: chartTokens }
}
export interface ChartLegendProps extends React.HTMLAttributes<HTMLDivElement> { items: { name: string; color: string }[]; chart?: ChartApi }
export function ChartLegend({ items, chart, ...props }: ChartLegendProps) {
  return <LegendRoot display="flex" flexWrap="wrap" gap="3" py="2" fontSize="sm" {...props}>{items.map((item, index) => <LegendButton key={`${item.name}-${index}`} type="button" display="inline-flex" alignItems="center" gap="2" color="fg.default" bg="transparent" border="0" cursor="pointer" opacity={chart?.opacity(index) ?? 1} {...(chart?.legendProps(index) ?? {})}><span style={{ width: 12, height: 3, background: item.color }} />{item.name}</LegendButton>)}</LegendRoot>
}
export interface ReferenceLineSpec { value: number; label?: string; color?: string; axis?: "left" | "right"; dashed?: boolean }
export interface CartesianGridProps { x0: number; x1: number; y0: number; y1: number; horizontal?: number[]; vertical?: number[] }
export interface ChartAxisProps { orientation: "bottom" | "left" | "right"; at: number; ticks: { pos: number; label: string }[] }
export interface CommonChartProps extends Omit<React.SVGProps<SVGSVGElement>, "color" | "height" | "width" | "mode"> { height?: number; showGrid?: boolean; showAxes?: boolean; legend?: boolean; highlight?: number | null; categories?: string[]; xTickFormat?: (label: string, index: number) => string; yTickFormat?: ChartFormat; referenceLines?: ReferenceLineSpec[] }
export interface LineChartProps extends CommonChartProps { series: ChartSeries[]; area?: boolean; gradient?: boolean; showDots?: boolean; dashed?: boolean; connectNulls?: boolean; seriesLabels?: boolean; rightTickFormat?: ChartFormat }
export interface AreaChartProps extends CommonChartProps { series: ChartSeries[]; mode?: "overlap" | "stacked" | "percent"; gradient?: boolean; showDots?: boolean; referenceArea?: { from: number; to: number; label?: string } }
export interface BarChartProps extends CommonChartProps { series: ChartSeries[]; mode?: "grouped" | "stacked" | "percent"; gap?: number; joined?: boolean }
interface PlotFrameProps {
  series: ChartSeries[]; categories?: string[]; height: number; showGrid: boolean; showAxes: boolean; highlight?: number | null; legend: boolean
  mode: "line" | "area" | "bar"; area?: boolean; areaGradient?: boolean; showDots?: boolean; dashed?: boolean
  barMode?: "grouped" | "stacked" | "percent"; areaMode?: "overlap" | "stacked" | "percent"; gap?: number; joined?: boolean
  xTickFormat?: (label: string, index: number) => string; yTickFormat?: ChartFormat; referenceLines?: ReferenceLineSpec[]
}
function PlotFrame({ series, categories, height, showGrid, showAxes, highlight, legend, mode, area, areaGradient = false, showDots = true, dashed, barMode = "grouped", areaMode = "overlap", gap = 0.3, joined = false, xTickFormat, yTickFormat = compactFormat, referenceLines = [] }: PlotFrameProps) {
  const chart = useChart({ series, highlight }), gradientId = React.useId().replace(/:/g, ""), W = 640, pad = { top: 16, right: 16, bottom: 30, left: 48 }, innerW = W - pad.left - pad.right, innerH = height - pad.top - pad.bottom
  const count = Math.max(1, ...series.map((item) => item.values.length))
  const values = [...series.flatMap((item) => item.values.filter((value): value is number => value != null && Number.isFinite(value))), ...referenceLines.map((line) => line.value)]
  const totals = Array.from({ length: count }, (_, index) => series.reduce((sum, item) => sum + Math.max(0, item.values[index] ?? 0), 0))
  const stackedMax = Math.max(1, ...totals)
  const percentMode = (mode === "bar" && barMode === "percent") || (mode === "area" && areaMode === "percent")
  const domain = percentMode ? [0, 100] as [number, number] : niceDomain(Math.min(0, ...values), Math.max(1, ...(mode === "bar" && barMode !== "grouped" || mode === "area" && areaMode !== "overlap" ? [stackedMax] : values)), 5).domain
  const x = (index: number) => pad.left + (count === 1 ? innerW / 2 : (index / (count - 1)) * innerW)
  const band = innerW / count
  const y = (value: number) => pad.top + innerH - ((value - domain[0]) / (domain[1] - domain[0] || 1)) * innerH
  const names = series.map((item, index) => ({ name: item.name ?? `Series ${index + 1}`, color: chart.colors[index]! }))
  const valueAt = (seriesIndex: number, index: number) => Math.max(0, series[seriesIndex]?.values[index] ?? 0)
  const normalized = (seriesIndex: number, index: number) => percentMode ? (totals[index] ? valueAt(seriesIndex, index) / totals[index]! * 100 : 0) : valueAt(seriesIndex, index)
  const cumulative = (seriesIndex: number, index: number) => series.slice(0, seriesIndex + 1).reduce((sum, _item, itemIndex) => sum + normalized(itemIndex, index), 0)
  return <Root width="100%"><svg viewBox={`0 0 ${W} ${height}`} width="100%" role="img" aria-label={`${mode === "bar" ? "Bar" : mode === "area" ? "Area" : "Line"} chart`}>
    {mode === "area" && areaGradient && <defs>{series.map((item, index) => <linearGradient key={index} id={`${gradientId}-${index}`} x1="0" x2="0" y1="0" y2="1"><stop offset="0%" stopColor={chart.colors[index]} stopOpacity="0.5" /><stop offset="100%" stopColor={chart.colors[index]} stopOpacity="0.05" /></linearGradient>)}</defs>}
    {showGrid && <g stroke="currentColor" opacity="0.12">{niceDomain(domain[0], domain[1], 5).ticks.filter((value) => value >= domain[0] && value <= domain[1]).map((value) => <line key={value} x1={pad.left} x2={W - pad.right} y1={y(value)} y2={y(value)} />)}</g>}
    {referenceLines.map((line, index) => <g key={`reference-${index}`}><line x1={pad.left} x2={W - pad.right} y1={y(line.value)} y2={y(line.value)} stroke={resolveColor(line.color ?? "danger", 0)} strokeDasharray={line.dashed ? "5 4" : undefined} strokeWidth="1.5" />{line.label && <text x={W - pad.right - 2} y={y(line.value) - 4} textAnchor="end" fill={resolveColor(line.color ?? "danger", 0)} fontSize="10">{line.label}</text>}</g>)}{showAxes && <g fill="currentColor" fontSize="10" opacity="0.8">{niceDomain(domain[0], domain[1], 5).ticks.filter((value) => value >= domain[0] && value <= domain[1]).map((value) => <text key={value} x={pad.left - 7} y={y(value) + 3} textAnchor="end">{yTickFormat(value)}</text>)}{Array.from({ length: count }, (_, index) => <text key={index} x={x(index)} y={height - 8} textAnchor="middle">{xTickFormat?.(categories?.[index] ?? String(index + 1), index) ?? (categories?.[index] ?? String(index + 1))}</text>)}</g>}
    {series.map((item, seriesIndex) => {
      if (mode === "bar") {
        const grouped = barMode === "grouped", slot = band / Math.max(1, grouped ? series.length : 1), width = slot * (joined ? 1 : 1 - Math.max(0, Math.min(0.9, gap)))
        return <g key={seriesIndex} opacity={chart.opacity(seriesIndex)}>{item.values.map((value, index) => { if (value == null || !Number.isFinite(value)) return null; const topValue = grouped ? value : cumulative(seriesIndex, index), bottomValue = grouped ? 0 : series.slice(0, seriesIndex).reduce((sum, _item, prevIndex) => sum + normalized(prevIndex, index), 0), left = pad.left + index * band + (grouped ? seriesIndex * slot : (band - width) / 2); return <rect key={index} x={left + (slot - width) / 2} y={Math.min(y(topValue), y(bottomValue))} width={width} height={Math.max(1, Math.abs(y(bottomValue) - y(topValue)))} fill={chart.colors[seriesIndex]!} rx="2" /> })}</g>
      }
      if (mode === "area") {
        const tops = item.values.map((value, index) => value == null ? null : areaMode === "overlap" ? value : cumulative(seriesIndex, index))
        const bottoms = item.values.map((value, index) => value == null ? null : areaMode === "overlap" || seriesIndex === 0 ? 0 : series.slice(0, seriesIndex).reduce((sum, _item, previous) => sum + normalized(previous, index), 0))
        const upper = tops.map((value, index) => value == null ? null : `${index === 0 || tops[index - 1] == null ? "M" : "L"}${x(index)},${y(value)}`).filter(Boolean).join(" ")
        const down = bottoms.map((value, reverseIndex) => { const index = bottoms.length - 1 - reverseIndex; return value == null || tops[index] == null ? null : `L${x(index)},${y(value)}` }).filter(Boolean).join(" ")
        const line = item.values.map((value, index) => value == null ? null : `${index === 0 || item.values[index - 1] == null ? "M" : "L"}${x(index)},${y(value)}`).filter(Boolean).join(" ")
        return <g key={seriesIndex} opacity={chart.opacity(seriesIndex)}><path d={`${upper} ${down} Z`} fill={areaGradient ? `url(#${gradientId}-${seriesIndex})` : chart.colors[seriesIndex]!} fillOpacity={areaGradient ? 1 : 0.18} /><path d={areaMode === "overlap" ? line : upper} fill="none" stroke={chart.colors[seriesIndex]!} strokeWidth="2" strokeLinejoin="round" />{showDots && item.values.map((value, index) => value == null ? null : <circle key={index} cx={x(index)} cy={y(areaMode === "overlap" ? value : tops[index] ?? 0)} r="3" fill="var(--indoku-colors-bg-surface)" stroke={chart.colors[seriesIndex]!} strokeWidth="2" />)}</g>
      }
      let pen = false
      const path = item.values.map((value, index) => { if (value == null || !Number.isFinite(value)) { pen = false; return null }; const command = `${pen ? "L" : "M"}${x(index)},${y(value)}`; pen = true; return command }).filter(Boolean).join(" ")
      const points = item.values.map((value, index) => value == null || !Number.isFinite(value) ? null : { x: x(index), y: y(value) }).filter((point) => point !== null) as { x: number; y: number }[]
      const first = points[0], last = points[points.length - 1]
      return <g key={seriesIndex} opacity={chart.opacity(seriesIndex)}><path d={path} fill="none" stroke={chart.colors[seriesIndex]!} strokeWidth="2" strokeDasharray={dashed || item.dashed ? "5 4" : undefined} strokeLinecap="round" strokeLinejoin="round" />{area && first && last && <path d={`${path} L${last.x},${pad.top + innerH} L${first.x},${pad.top + innerH} Z`} fill={chart.colors[seriesIndex]!} opacity="0.12" />}{showDots && points.map((point, index) => <circle key={index} cx={point.x} cy={point.y} r="3" fill="var(--indoku-colors-bg-surface)" stroke={chart.colors[seriesIndex]!} strokeWidth="2" />)}</g>
    })}
  </svg>{legend && <ChartLegend items={names} chart={chart} />}</Root>
}
export function LineChart({ series, categories, height = 220, showGrid = true, showAxes = true, legend = false, highlight, area = false, showDots = true, dashed, xTickFormat, yTickFormat, referenceLines, ...props }: LineChartProps) { return <PlotFrame series={series} categories={categories} height={height} showGrid={showGrid} showAxes={showAxes} legend={legend} highlight={highlight} mode="line" area={area} showDots={showDots} dashed={dashed} xTickFormat={xTickFormat} yTickFormat={yTickFormat} referenceLines={referenceLines} {...props} /> }
export function AreaChart({ series, categories, height = 220, showGrid = true, showAxes = true, legend = false, highlight, mode = "overlap", gradient = true, showDots = false, xTickFormat, yTickFormat, referenceLines, ...props }: AreaChartProps) { return <PlotFrame series={series} categories={categories} height={height} showGrid={showGrid} showAxes={showAxes} legend={legend} highlight={highlight} mode="area" areaMode={mode} areaGradient={gradient} showDots={showDots} xTickFormat={xTickFormat} yTickFormat={yTickFormat} referenceLines={referenceLines} {...props} /> }
export function BarChart({ series, categories, height = 220, showGrid = true, showAxes = true, legend = false, highlight, mode = "grouped", gap = 0.3, joined = false, xTickFormat, yTickFormat, referenceLines, ...props }: BarChartProps) { return <PlotFrame series={series} categories={categories} height={height} showGrid={showGrid} showAxes={showAxes} legend={legend} highlight={highlight} mode="bar" barMode={mode} gap={gap} joined={joined} xTickFormat={xTickFormat} yTickFormat={yTickFormat} referenceLines={referenceLines} {...props} /> }
export interface PieDatum { name: string; value: number; color?: string }
export interface PieChartProps extends Omit<React.SVGProps<SVGSVGElement>, "color" | "height"> { data: PieDatum[]; size?: number; innerRadiusRatio?: number; padAngle?: number; detached?: number[]; detachDistance?: number; radialText?: { label: string; sublabel?: string }; legend?: boolean }
export function PieChart({ data, size = 220, innerRadiusRatio = 0, padAngle = 0, detached = [], detachDistance = 8, radialText, legend = false, ...props }: PieChartProps) {
  const chart = useChart({ series: data }), total = data.reduce((sum, item) => sum + Math.max(0, item.value), 0) || 1, center = size / 2, radius = center - detachDistance - 2, inner = radius * innerRadiusRatio, pad = padAngle * Math.PI / 180
  let angle = -Math.PI / 2
  const slices = data.map((item, index) => { const sweep = Math.max(0, item.value) / total * Math.PI * 2, a0 = angle + pad / 2, a1 = angle + sweep - pad / 2, mid = angle + sweep / 2; angle += sweep; const offset = detached.includes(index) ? detachDistance : 0, cx = center + offset * Math.cos(mid), cy = center + offset * Math.sin(mid), point = (r: number, a: number) => `${cx + r * Math.cos(a)},${cy + r * Math.sin(a)}`, large = a1 - a0 > Math.PI ? 1 : 0; return { item, index, path: inner ? `M${point(inner, a0)} L${point(radius, a0)} A${radius},${radius} 0 ${large} 1 ${point(radius, a1)} L${point(inner, a1)} A${inner},${inner} 0 ${large} 0 ${point(inner, a0)} Z` : `M${cx},${cy} L${point(radius, a0)} A${radius},${radius} 0 ${large} 1 ${point(radius, a1)} Z` } })
  return <Root display="flex" flexDirection="column" alignItems="center" gap="2"><svg viewBox={`0 0 ${size} ${size}`} width={`${size}px`} height={`${size}px`} role="img" aria-label="Pie chart" {...props}>{slices.map(({ item, index, path }) => <path key={index} d={path} fill={resolveColor(item.color, index)} opacity={chart.opacity(index)} />)}{radialText && <g textAnchor="middle" fill="currentColor"><text x={center} y={center} fontSize="18" fontWeight="600">{radialText.label}</text>{radialText.sublabel && <text x={center} y={center + 18} fontSize="10">{radialText.sublabel}</text>}</g>}</svg>{legend && <ChartLegend items={data.map((item, index) => ({ name: item.name, color: resolveColor(item.color, index) }))} chart={chart} />}</Root>
}
export interface DonutChartProps extends PieChartProps {}
export function DonutChart({ innerRadiusRatio = 0.6, ...props }: DonutChartProps) { return <PieChart innerRadiusRatio={innerRadiusRatio} {...props} /> }
export interface SparklineProps extends Omit<React.SVGProps<SVGSVGElement>, "color" | "height" | "width" | "values" | "format"> { values: number[]; width?: number; height?: number; color?: string; area?: boolean; interactive?: boolean; format?: ChartFormat }
export function Sparkline({ values, width = 120, height = 32, color, area = false, interactive = false, format = compactFormat, ...props }: SparklineProps) {
  const [hover, setHover] = React.useState<number | null>(null), stroke = resolveColor(color, 0), low = Math.min(...values, 0), high = Math.max(...values, 1), pad = 3
  const points = values.map((value, index) => [values.length > 1 ? pad + index / (values.length - 1) * (width - 2 * pad) : width / 2, height - pad - (value - low) / (high - low || 1) * (height - 2 * pad)] as const), d = points.map(([x, y], index) => `${index ? "L" : "M"}${x},${y}`).join(" "), active = hover == null ? null : points[hover]
  return <svg viewBox={`0 0 ${width} ${height}`} width={`${width}px`} height={`${height}px`} role="img" aria-label={`Sparkline: ${values.map(format).join(", ")}`} onPointerLeave={interactive ? () => setHover(null) : undefined} onPointerMove={interactive ? (event) => { const rect = event.currentTarget.getBoundingClientRect(); const position = ((event.clientX - rect.left) / Math.max(1, rect.width)) * width; setHover(Math.min(values.length - 1, Math.max(0, Math.round((position - pad) / (width - pad * 2) * (values.length - 1)))))} : undefined} {...props}>{area && <path d={`${d} L${points[points.length - 1]?.[0] ?? 0},${height} L${points[0]?.[0] ?? 0},${height} Z`} fill={stroke} opacity="0.12" />}<path d={d} fill="none" stroke={stroke} strokeWidth="1.75" strokeLinecap="round" strokeLinejoin="round" />{active && <g><circle cx={active[0]} cy={active[1]} r="3" fill={stroke} /><text x={active[0]} y={active[1] - 6} fontSize="10" fill="currentColor">{format(values[hover!]!)}</text></g>}</svg>
}
export interface RadialTextProps { x: number; y: number; label: string; sublabel?: string }
export function RadialText({ x, y, label, sublabel }: RadialTextProps) { return <g textAnchor="middle" fill="currentColor"><text x={x} y={y} fontSize="18" fontWeight="600">{label}</text>{sublabel && <text x={x} y={y + 18} fontSize="10">{sublabel}</text>}</g> }

export interface HistogramProps extends Omit<BarChartProps, "series" | "categories" | "mode" | "joined" | "values"> { values: number[]; bins?: number; color?: string; name?: string }
export function Histogram({ values, bins = 10, color, name = "Count", ...props }: HistogramProps) {
  const finite = values.filter(Number.isFinite), min = Math.min(...finite, 0), max = Math.max(...finite, 1), count = Math.max(1, Math.floor(bins)), width = (max - min || 1) / count
  const frequencies = Array.from({ length: count }, () => 0)
  finite.forEach((value) => { const index = Math.min(count - 1, Math.max(0, Math.floor((value - min) / width))); frequencies[index] = (frequencies[index] ?? 0) + 1 })
  const categories = frequencies.map((_, index) => String(+((min + index * width).toPrecision(4))))
  return <BarChart {...props} series={[{ name, color, values: frequencies }]} categories={categories} joined />
}
export interface BarSegmentDatum { name: string; value: number; color?: string }
export interface BarSegmentProps extends React.HTMLAttributes<HTMLDivElement> { data: BarSegmentDatum[]; barHeight?: number; showLegend?: boolean; format?: ChartFormat }
export function BarSegment({ data, barHeight = 12, showLegend = true, format = compactFormat, ...props }: BarSegmentProps) {
  const chart = useChart({ series: data }), total = data.reduce((sum, item) => sum + Math.max(0, item.value), 0) || 1
  return <Root {...props} color="fg.default"><div role="img" aria-label={data.map((item) => `${item.name} ${item.value}`).join(", ")} style={{ display: "flex", width: "100%", height: barHeight, overflow: "hidden", borderRadius: 999, gap: 2 }}>{data.map((item, index) => <div key={item.name} style={{ flex: `${Math.max(0, item.value) / total} 1 0`, minWidth: item.value > 0 ? 1 : 0, background: chart.colors[index], opacity: chart.opacity(index) }} />)}</div>{showLegend && <LegendRoot display="flex" flexWrap="wrap" gap="3" mt="3" fontSize="xs">{data.map((item, index) => <LegendButton key={item.name} type="button" display="inline-flex" alignItems="center" gap="2" bg="transparent" color="fg.default" border="0" cursor="pointer" tabIndex={0} {...chart.legendProps(index)}><span style={{ width: 10, height: 10, borderRadius: 2, background: chart.colors[index] }} />{item.name}<strong>{format(item.value)}</strong><MutedPercent value={item.value / total} /></LegendButton>)}</LegendRoot>}</Root>
}
function MutedPercent({ value }: { value: number }) { return <span style={{ opacity: 0.7 }}>{(value * 100).toFixed(1)}%</span> }
export interface ScatterPoint { x: number; y: number }
export interface ScatterSeries { name?: string; color?: string; points: ScatterPoint[] }
export interface ScatterChartProps extends Omit<CommonChartProps, "categories"> { series: ScatterSeries[]; trendLine?: boolean; connect?: boolean; dotSize?: number }
export function ScatterChart({ series, height = 240, showGrid = true, showAxes = true, legend = false, highlight, trendLine = false, connect = false, dotSize = 4, xTickFormat, yTickFormat = compactFormat, referenceLines = [], ...props }: ScatterChartProps) {
  const chart = useChart({ series, highlight }), W = 640, pad = { top: 16, right: 16, bottom: 30, left: 48 }, innerW = W - pad.left - pad.right, innerH = height - pad.top - pad.bottom
  const all = series.flatMap((item) => item.points).filter((point) => Number.isFinite(point.x) && Number.isFinite(point.y)), xd = niceDomain(Math.min(0, ...all.map((point) => point.x)), Math.max(1, ...all.map((point) => point.x))), yd = niceDomain(Math.min(0, ...all.map((point) => point.y), ...referenceLines.map((line) => line.value)), Math.max(1, ...all.map((point) => point.y), ...referenceLines.map((line) => line.value)))
  const x = (value: number) => pad.left + (value - xd.domain[0]) / (xd.domain[1] - xd.domain[0] || 1) * innerW, y = (value: number) => pad.top + innerH - (value - yd.domain[0]) / (yd.domain[1] - yd.domain[0] || 1) * innerH
  return <Root {...props} width="100%"><svg viewBox={`0 0 ${W} ${height}`} width="100%" role="img" aria-label="Scatter chart">{showGrid && <g stroke="currentColor" opacity="0.12">{xd.ticks.map((value) => <line key={`x${value}`} x1={x(value)} x2={x(value)} y1={pad.top} y2={height - pad.bottom} />)}{yd.ticks.map((value) => <line key={`y${value}`} x1={pad.left} x2={W - pad.right} y1={y(value)} y2={y(value)} />)}</g>}{referenceLines.map((line, index) => <g key={`reference-${index}`}><line x1={pad.left} x2={W - pad.right} y1={y(line.value)} y2={y(line.value)} stroke={resolveColor(line.color ?? "danger", 0)} strokeDasharray={line.dashed ? "5 4" : undefined} strokeWidth="1.5" />{line.label && <text x={W - pad.right - 2} y={y(line.value) - 4} textAnchor="end" fill={resolveColor(line.color ?? "danger", 0)} fontSize="10">{line.label}</text>}</g>)}{showAxes && <g fill="currentColor" fontSize="10" opacity="0.8">{xd.ticks.map((value, index) => <text key={value} x={x(value)} y={height - 8} textAnchor="middle">{xTickFormat?.(String(value), index) ?? value}</text>)}{yd.ticks.map((value) => <text key={value} x={pad.left - 7} y={y(value) + 3} textAnchor="end">{yTickFormat(value)}</text>)}</g>}{series.map((item, index) => { const points = item.points.filter((point) => Number.isFinite(point.x) && Number.isFinite(point.y)); let regression: string | null = null; if (trendLine && points.length > 1) { const meanX = points.reduce((sum, point) => sum + point.x, 0) / points.length, meanY = points.reduce((sum, point) => sum + point.y, 0) / points.length, denom = points.reduce((sum, point) => sum + (point.x - meanX) ** 2, 0), slope = denom ? points.reduce((sum, point) => sum + (point.x - meanX) * (point.y - meanY), 0) / denom : 0, intercept = meanY - slope * meanX; regression = `M${x(xd.domain[0])},${y(slope * xd.domain[0] + intercept)} L${x(xd.domain[1])},${y(slope * xd.domain[1] + intercept)}` } return <g key={item.name ?? index} opacity={chart.opacity(index)}>{connect && <polyline points={points.map((point) => `${x(point.x)},${y(point.y)}`).join(" ")} fill="none" stroke={chart.colors[index]} strokeWidth="1.5" />}{regression && <path d={regression} fill="none" stroke={chart.colors[index]} strokeDasharray="5 4" strokeWidth="1.5" />}{points.map((point, pointIndex) => <circle key={pointIndex} cx={x(point.x)} cy={y(point.y)} r={dotSize} fill={chart.colors[index]} />)}</g>})}</svg>{legend && <ChartLegend items={series.map((item, index) => ({ name: item.name ?? `Series ${index + 1}`, color: chart.colors[index]! }))} chart={chart} />}</Root>
}

export interface RadarChartProps extends Omit<React.SVGProps<SVGSVGElement>, "color" | "height" | "width"> { axes: string[]; series: ChartSeries[]; size?: number; levels?: number; grid?: "polygon" | "circle" | "filled"; pointLabels?: boolean; max?: number; legend?: boolean; highlight?: number | null }
export function RadarChart({ axes, series, size = 300, levels = 4, grid = "polygon", pointLabels = true, max, legend = false, highlight, ...props }: RadarChartProps) {
  const chart = useChart({ series, highlight }), center = size / 2, radius = center - (pointLabels ? 34 : 12), levelCount = Math.max(1, levels), axisCount = Math.max(3, axes.length), maximum = max ?? Math.max(1, ...series.flatMap((item) => item.values.filter((value): value is number => value != null && Number.isFinite(value))))
  const angle = (index: number) => -Math.PI / 2 + index / axisCount * Math.PI * 2
  const point = (index: number, r: number) => [center + r * Math.cos(angle(index)), center + r * Math.sin(angle(index))] as const
  const polygon = (level: number) => Array.from({ length: axisCount }, (_, index) => point(index, radius * level / levelCount).join(",")).join(" ")
  return <Root display="flex" flexDirection="column" alignItems="center" gap="2"><svg viewBox={`0 0 ${size} ${size}`} width={`${size}px`} height={`${size}px`} role="img" aria-label="Radar chart" {...props}><g stroke="currentColor" strokeWidth="1" opacity="0.15" fill="none">{Array.from({ length: levelCount }, (_, index) => levelCount - index).map((level) => grid === "circle" ? <circle key={level} cx={center} cy={center} r={radius * level / levelCount} /> : <polygon key={level} points={polygon(level)} fill={grid === "filled" && level % 2 ? "var(--indoku-colors-bg-muted)" : "none"} />)}{Array.from({ length: axisCount }, (_, index) => <line key={index} x1={center} y1={center} x2={point(index, radius)[0]} y2={point(index, radius)[1]} />)}</g>{series.map((item, seriesIndex) => { const points = Array.from({ length: axisCount }, (_, index) => point(index, radius * Math.max(0, Math.min(1, Number(item.values[index] ?? 0) / maximum)))); return <g key={item.name ?? seriesIndex} opacity={chart.opacity(seriesIndex)}><polygon points={points.map((xy) => xy.join(",")).join(" ")} fill={chart.colors[seriesIndex]} fillOpacity="0.18" stroke={chart.colors[seriesIndex]} strokeWidth="2" strokeLinejoin="round" />{points.map(([x, y], index) => <circle key={index} cx={x} cy={y} r="3" fill={chart.colors[seriesIndex]} />)}</g>})}{pointLabels && <g fill="currentColor" fontSize="10">{axes.map((label, index) => { const [x, y] = point(index, radius + 14); return <text key={label} x={x} y={y + 3} textAnchor={Math.abs(x - center) < 4 ? "middle" : x > center ? "start" : "end"}>{label}</text> })}</g>}</svg>{legend && <ChartLegend items={series.map((item, index) => ({ name: item.name ?? `Series ${index + 1}`, color: chart.colors[index]! }))} chart={chart} />}</Root>
}

export interface RangeDatum { label: string; min: number; max: number }
export interface RangeBarChartProps extends Omit<CommonChartProps, "legend" | "highlight" | "categories"> { data: RangeDatum[]; color?: string; gap?: number }
export function RangeBarChart({ data, color, height = 220, gap = 0.4, showGrid = true, showAxes = true, xTickFormat, yTickFormat = compactFormat, referenceLines = [], ...props }: RangeBarChartProps) {
  const W = 640, pad = { top: 16, right: 16, bottom: 30, left: 48 }, innerW = W - pad.left - pad.right, innerH = height - pad.top - pad.bottom, min = Math.min(...data.map((item) => item.min), 0), max = Math.max(...data.map((item) => item.max), ...referenceLines.map((line) => line.value), 1), domain = niceDomain(Math.min(min, ...referenceLines.map((line) => line.value)), max), x = (index: number) => pad.left + (index + 0.5) * innerW / Math.max(1, data.length), y = (value: number) => pad.top + innerH - (value - domain.domain[0]) / (domain.domain[1] - domain.domain[0] || 1) * innerH, fill = resolveColor(color, 0), barWidth = innerW / Math.max(1, data.length) * (1 - Math.max(0, Math.min(0.9, gap)))
  return <Root {...props} width="100%"><svg viewBox={`0 0 ${W} ${height}`} width="100%" role="img" aria-label="Range bar chart">{showGrid && <g stroke="currentColor" opacity="0.12">{domain.ticks.map((value) => <line key={value} x1={pad.left} x2={W - pad.right} y1={y(value)} y2={y(value)} />)}</g>}{data.map((item, index) => <rect key={item.label} x={x(index) - barWidth / 2} y={y(Math.max(item.min, item.max))} width={barWidth} height={Math.max(1, Math.abs(y(item.min) - y(item.max)))} rx="3" fill={fill} />)}{referenceLines.map((line, index) => <g key={`reference-${index}`}><line x1={pad.left} x2={W - pad.right} y1={y(line.value)} y2={y(line.value)} stroke={resolveColor(line.color ?? "danger", 0)} strokeDasharray={line.dashed ? "5 4" : undefined} strokeWidth="1.5" />{line.label && <text x={W - pad.right - 2} y={y(line.value) - 4} textAnchor="end" fill={resolveColor(line.color ?? "danger", 0)} fontSize="10">{line.label}</text>}</g>)}{showAxes && <g fill="currentColor" fontSize="10" opacity="0.8">{domain.ticks.map((value) => <text key={value} x={pad.left - 7} y={y(value) + 3} textAnchor="end">{yTickFormat(value)}</text>)}{data.map((item, index) => <text key={item.label} x={x(index)} y={height - 8} textAnchor="middle">{xTickFormat?.(item.label, index) ?? item.label}</text>)}</g>}</svg></Root>
}
export interface CandleDatum { label: string; open: number; high: number; low: number; close: number }
export interface CandlestickChartProps extends Omit<CommonChartProps, "legend" | "highlight" | "categories"> { data: CandleDatum[]; upColor?: string; downColor?: string }
export function CandlestickChart({ data, upColor = "success", downColor = "danger", height = 240, showGrid = true, showAxes = true, xTickFormat, yTickFormat = compactFormat, referenceLines = [], ...props }: CandlestickChartProps) {
  const W = 640, pad = { top: 16, right: 16, bottom: 30, left: 48 }, innerW = W - pad.left - pad.right, innerH = height - pad.top - pad.bottom, values = data.flatMap((item) => [item.high, item.low]), domain = niceDomain(Math.min(...values, ...referenceLines.map((line) => line.value), 0), Math.max(...values, ...referenceLines.map((line) => line.value), 1)), x = (index: number) => pad.left + (index + 0.5) * innerW / Math.max(1, data.length), y = (value: number) => pad.top + innerH - (value - domain.domain[0]) / (domain.domain[1] - domain.domain[0] || 1) * innerH, width = innerW / Math.max(1, data.length) * 0.6
  return <Root {...props} width="100%"><svg viewBox={`0 0 ${W} ${height}`} width="100%" role="img" aria-label="Candlestick chart">{showGrid && <g stroke="currentColor" opacity="0.12">{domain.ticks.map((value) => <line key={value} x1={pad.left} x2={W - pad.right} y1={y(value)} y2={y(value)} />)}</g>}{data.map((item) => { const rising = item.close >= item.open, stroke = resolveColor(rising ? upColor : downColor, 0), index = data.indexOf(item), top = y(Math.max(item.open, item.close)), bottom = y(Math.min(item.open, item.close)); return <g key={`${item.label}-${index}`} stroke={stroke} fill={stroke}><line x1={x(index)} x2={x(index)} y1={y(item.high)} y2={y(item.low)} strokeWidth="1.5" /><rect x={x(index) - width / 2} y={top} width={width} height={Math.max(1.5, bottom - top)} rx="1" /></g>})}{referenceLines.map((line, index) => <g key={`reference-${index}`}><line x1={pad.left} x2={W - pad.right} y1={y(line.value)} y2={y(line.value)} stroke={resolveColor(line.color ?? "danger", 0)} strokeDasharray={line.dashed ? "5 4" : undefined} strokeWidth="1.5" />{line.label && <text x={W - pad.right - 2} y={y(line.value) - 4} textAnchor="end" fill={resolveColor(line.color ?? "danger", 0)} fontSize="10">{line.label}</text>}</g>)}{showAxes && <g fill="currentColor" fontSize="10" opacity="0.8">{domain.ticks.map((value) => <text key={value} x={pad.left - 7} y={y(value) + 3} textAnchor="end">{yTickFormat(value)}</text>)}{data.map((item, index) => <text key={item.label} x={x(index)} y={height - 8} textAnchor="middle">{xTickFormat?.(item.label, index) ?? item.label}</text>)}</g>}</svg></Root>
}

export function CartesianGrid({ x0, x1, y0, y1, horizontal = [], vertical = [] }: CartesianGridProps) { return <g stroke="var(--indoku-colors-border-subtle)" strokeWidth="1" opacity="0.6">{horizontal.map((y, index) => <line key={`h${index}`} x1={x0} x2={x1} y1={y} y2={y} />)}{vertical.map((x, index) => <line key={`v${index}`} x1={x} x2={x} y1={y0} y2={y1} />)}</g> }
export function ChartAxis({ orientation, at, ticks }: ChartAxisProps) { return <g fill="var(--indoku-colors-fg-muted)" fontSize="10">{ticks.map((tick, index) => orientation === "bottom" ? <text key={index} x={tick.pos} y={at + 14} textAnchor="middle">{tick.label}</text> : <text key={index} x={at + (orientation === "left" ? -7 : 7)} y={tick.pos + 3} textAnchor={orientation === "left" ? "end" : "start"}>{tick.label}</text>)}</g> }
