import * as React from "react"
import { Button } from "./button"
import { Checkbox } from "./checkbox"
import { indoku } from "../primitives/indoku"

export interface DataTableColumn<T> { id: string; header: React.ReactNode; label?: string; accessor?: keyof T | ((row: T) => unknown); cell?: (info: { row: T; value: unknown; index: number }) => React.ReactNode; sortable?: boolean; hideable?: boolean; align?: "start" | "center" | "end"; width?: string | number }
export type SortDirection = "asc" | "desc"
export interface SortState { columnId: string; direction: SortDirection }
export interface DataTableLabels { search: string; columns: string; noResults: string; previous: string; next: string; selectAll: string; selectRow: string; page: (page: number, pageCount: number) => string; selected: (selected: number, total: number) => string; rows: (total: number) => string }
const defaultLabels: DataTableLabels = { search: "Search...", columns: "Columns", noResults: "No results.", previous: "Previous", next: "Next", selectAll: "Select all rows on this page", selectRow: "Select row", page: (page, total) => `Page ${page} of ${total}`, selected: (selected, total) => `${selected} of ${total} row(s) selected.`, rows: (total) => `${total} row(s)` }
interface Entry { id: string; index: number; row: any }
interface ContextValue { columns: DataTableColumn<any>[]; visibleColumns: DataTableColumn<any>[]; entries: Entry[]; totalRows: number; page: number; pageCount: number; pageSize: number; setPage(page: number): void; sort: SortState | null; toggleSort(id: string): void; search: string; setSearch(value: string): void; selectable: boolean; selectedIds: Set<string>; selectedCount: number; pageSelection: boolean | "indeterminate"; toggleRow(id: string): void; togglePage(): void; hidden: Set<string>; toggleColumn(id: string): void; labels: DataTableLabels }
const Context = React.createContext<ContextValue | null>(null)
export function useDataTable() { const value = React.useContext(Context); if (!value) throw new Error("DataTable parts must be nested inside DataTable.Root"); return value }
function valueOf<T>(row: T, column: DataTableColumn<T>): unknown { if (typeof column.accessor === "function") return column.accessor(row); if (column.accessor !== undefined) return row[column.accessor]; return (row as Record<string, unknown>)[column.id] }
function compare(a: unknown, b: unknown) { if (typeof a === "number" && typeof b === "number") return a - b; if (a instanceof Date && b instanceof Date) return a.getTime() - b.getTime(); if (typeof a === "boolean" && typeof b === "boolean") return Number(a) - Number(b); return String(a ?? "").localeCompare(String(b ?? ""), undefined, { numeric: true, sensitivity: "base" }) }
function format(value: unknown): React.ReactNode { if (value == null) return ""; if (value instanceof Date) return value.toLocaleDateString(); return String(value) }
const RootElement = indoku("section"), ToolbarElement = indoku("div"), SearchElement = indoku("input"), ToggleElement = indoku("label"), TableElement = indoku("table"), Head = indoku("thead"), Body = indoku("tbody"), Row = indoku("tr"), Header = indoku("th"), Cell = indoku("td"), PaginationElement = indoku("nav")
export interface RootProps<T> extends React.HTMLAttributes<HTMLElement> { data: T[]; columns: DataTableColumn<T>[]; getRowId?: (row: T, index: number) => string; pageSize?: number; defaultSort?: SortState; selectable?: boolean; onSelectionChange?: (rows: T[]) => void; labels?: Partial<DataTableLabels>; children?: React.ReactNode }
export function Root<T>({ data, columns, getRowId, pageSize = 10, defaultSort, selectable = false, onSelectionChange, labels: overrides, children, ...props }: RootProps<T>) {
  const [page, setPage] = React.useState(0), [sort, setSort] = React.useState<SortState | null>(defaultSort ?? null), [search, setSearch] = React.useState(""), [hidden, setHidden] = React.useState<Set<string>>(new Set()), [selectedIds, setSelectedIds] = React.useState<Set<string>>(new Set())
  const labels = React.useMemo(() => ({ ...defaultLabels, ...overrides }), [overrides])
  const entries = React.useMemo(() => {
    let result = data.map((row, index) => ({ id: getRowId?.(row, index) ?? String(index), index, row })).filter(({ row }) => !search || columns.some((column) => String(valueOf(row, column) ?? "").toLowerCase().includes(search.toLowerCase())))
    if (sort) { const column = columns.find((item) => item.id === sort.columnId); if (column) result = [...result].sort((a, b) => compare(valueOf(a.row, column), valueOf(b.row, column)) * (sort.direction === "asc" ? 1 : -1)) }
    return result
  }, [data, columns, getRowId, search, sort])
  const pageCount = Math.max(1, Math.ceil(entries.length / Math.max(1, pageSize))), safePage = Math.min(page, pageCount - 1)
  React.useEffect(() => { if (safePage !== page) setPage(safePage) }, [safePage, page])
  const pageEntries = entries.slice(safePage * pageSize, (safePage + 1) * pageSize)
  const pageSelection = pageEntries.length > 0 && pageEntries.every((entry) => selectedIds.has(entry.id)) ? true : pageEntries.some((entry) => selectedIds.has(entry.id)) ? "indeterminate" : false
  const toggleSort = (id: string) => setSort((current) => current?.columnId === id ? { columnId: id, direction: current.direction === "asc" ? "desc" : "asc" } : { columnId: id, direction: "asc" })
  const toggleRow = (id: string) => setSelectedIds((current) => { const next = new Set(current); next.has(id) ? next.delete(id) : next.add(id); return next })
  const togglePage = () => setSelectedIds((current) => { const next = new Set(current); const all = pageEntries.length > 0 && pageEntries.every((entry) => next.has(entry.id)); pageEntries.forEach((entry) => all ? next.delete(entry.id) : next.add(entry.id)); return next })
  const toggleColumn = (id: string) => setHidden((current) => { const next = new Set(current); next.has(id) ? next.delete(id) : next.add(id); return next })
  React.useEffect(() => { onSelectionChange?.(data.filter((row, index) => selectedIds.has(getRowId?.(row, index) ?? String(index)))) }, [selectedIds, data, getRowId, onSelectionChange])
  const context = React.useMemo<ContextValue>(() => ({ columns, visibleColumns: columns.filter((column) => !hidden.has(column.id)), entries: pageEntries, totalRows: entries.length, page: safePage, pageCount, pageSize, setPage, sort, toggleSort, search, setSearch, selectable, selectedIds, selectedCount: selectedIds.size, pageSelection, toggleRow, togglePage, hidden, toggleColumn, labels }), [columns, hidden, pageEntries, entries.length, safePage, pageCount, pageSize, sort, search, selectable, selectedIds, pageSelection, labels])
  return <Context.Provider value={context}><RootElement display="flex" flexDirection="column" gap="3" {...props}>{children}</RootElement></Context.Provider>
}
export type ToolbarProps = React.HTMLAttributes<HTMLDivElement>
export function Toolbar(props: ToolbarProps) { return <ToolbarElement role="toolbar" display="flex" alignItems="center" gap="2" flexWrap="wrap" {...props} /> }
export type SearchProps = Omit<React.InputHTMLAttributes<HTMLInputElement>, "value" | "onChange" | "type">
export function Search(props: SearchProps) { const table = useDataTable(); return <SearchElement type="search" maxWidth="320px" placeholder={table.labels.search} aria-label={table.labels.search} value={table.search} onChange={(event: React.ChangeEvent<HTMLInputElement>) => table.setSearch(event.target.value)} border="1px solid" borderColor="border.subtle" borderRadius="md" bg="bg.surface" color="fg.default" px="3" py="2" fontSize="sm" {...props} /> }
export function ColumnToggle() { const table = useDataTable(); return <details style={{ marginInlineStart: "auto", position: "relative" }}><summary style={{ cursor: "pointer", fontSize: 13 }}>{table.labels.columns}</summary><div style={{ position: "absolute", right: 0, zIndex: 5, minWidth: 180, padding: 8, border: "1px solid var(--indoku-colors-border-subtle)", borderRadius: 8, background: "var(--indoku-colors-bg-surface)" }}>{table.columns.filter((column) => column.hideable !== false).map((column) => <ToggleElement key={column.id} display="flex" gap="2" alignItems="center" py="1" fontSize="sm"><Checkbox size="sm" checked={!table.hidden.has(column.id)} onCheckedChange={() => table.toggleColumn(column.id)} /><span>{column.label ?? (typeof column.header === "string" ? column.header : column.id)}</span></ToggleElement>)}</div></details> }
export interface TableProps extends React.HTMLAttributes<HTMLDivElement> {}
export function Table(props: TableProps) { const table = useDataTable(), colSpan = table.visibleColumns.length + (table.selectable ? 1 : 0); return <div style={{ overflowX: "auto", border: "1px solid var(--indoku-colors-border-subtle)", borderRadius: 8 }} {...props}><TableElement width="100%" borderCollapse="collapse" fontSize="sm"><Head bg="bg.subtle"><Row>{table.selectable && <Header scope="col"><Checkbox size="sm" checked={table.pageSelection === true} indeterminate={table.pageSelection === "indeterminate"} onCheckedChange={table.togglePage}><span style={{ position: "absolute", width: 1, height: 1, overflow: "hidden", clip: "rect(0,0,0,0)" }}>{table.labels.selectAll}</span></Checkbox></Header>}{table.visibleColumns.map((column) => { const direction = table.sort?.columnId === column.id ? table.sort.direction : null; return <Header key={column.id} scope="col" textAlign={column.align ?? "start"} width={column.width} aria-sort={direction ? direction === "asc" ? "ascending" : "descending" : column.sortable ? "none" : undefined} p="10px" borderBottom="1px solid" borderColor="border.subtle">{column.sortable ? <Button size="xs" variant="ghost" onClick={() => table.toggleSort(column.id)}>{column.header} {direction === "asc" ? "↑" : direction === "desc" ? "↓" : "↕"}</Button> : column.header}</Header>})}</Row></Head><Body>{table.entries.length === 0 ? <Row><Cell colSpan={colSpan} textAlign="center" py="8" color="fg.muted">{table.labels.noResults}</Cell></Row> : table.entries.map((entry) => <Row key={entry.id} bg={table.selectedIds.has(entry.id) ? "bg.subtle" : "transparent"}>{table.selectable && <Cell p="10px"><Checkbox size="sm" checked={table.selectedIds.has(entry.id)} onCheckedChange={() => table.toggleRow(entry.id)}><span style={{ position: "absolute", width: 1, height: 1, overflow: "hidden", clip: "rect(0,0,0,0)" }}>{`${table.labels.selectRow}: ${entry.id}`}</span></Checkbox></Cell>}{table.visibleColumns.map((column) => { const value = valueOf(entry.row, column); return <Cell key={column.id} p="10px" borderBottom="1px solid" borderColor="border.subtle" textAlign={column.align ?? "start"}>{column.cell ? column.cell({ row: entry.row, value, index: entry.index }) : format(value)}</Cell>})}</Row>)}</Body></TableElement></div> }
export function Pagination(props: React.HTMLAttributes<HTMLElement>) { const table = useDataTable(); return <PaginationElement aria-label="Pagination" display="flex" alignItems="center" justifyContent="space-between" gap="4" fontSize="sm" {...props}><span>{table.selectable ? table.labels.selected(table.selectedCount, table.totalRows) : table.labels.rows(table.totalRows)}</span><span style={{ display: "flex", alignItems: "center", gap: 12 }}><span aria-live="polite">{table.labels.page(table.page + 1, table.pageCount)}</span><Button size="sm" variant="outline" disabled={table.page <= 0} onClick={() => table.setPage(table.page - 1)}>{table.labels.previous}</Button><Button size="sm" variant="outline" disabled={table.page >= table.pageCount - 1} onClick={() => table.setPage(table.page + 1)}>{table.labels.next}</Button></span></PaginationElement> }
export const DataTable = Object.assign(Root, { Root, Toolbar, Search, ColumnToggle, Table, Pagination })
